local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()

local w = library:CreateWindow("ElEmDee Hub") -- Creates the window
local b = w:CreateFolder("AutoFarm") -- Creates the folder(U will put here your buttons,etc)
local misc = w:CreateFolder('Misc')


b:Toggle("Auto Tap",function(bool)
   getgenv().starttap = bool
   print('Action is: ', bool)
   if bool then
       dotap()
   end
end)

b:Toggle("Auto Rebirth",function(bool)
   getgenv().startrebirth = bool
   print('Action is: ', bool)
   if bool then
       dorebirth()
   end
end)


misc:DestroyGui()

function dotap()
    spawn(function()
        while getgenv().starttap == true  do 
game:GetService("ReplicatedStorage").Remotes.Tap:FireServer()
wait()
        end
    end)
end




function dorebirth()
    spawn(function()
        while getgenv().startrebirth == true  do 
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = 4
}

game:GetService("ReplicatedStorage").Remotes.Rebirth:FireServer(unpack(args))

wait()

local args = {
    [1] = 3
}

game:GetService("ReplicatedStorage").Remotes.Rebirth:FireServer(unpack(args))

wait()

local args = {
    [1] = 2
}

game:GetService("ReplicatedStorage").Remotes.Rebirth:FireServer(unpack(args))

wait()

local args = {
    [1] = 1
}

game:GetService("ReplicatedStorage").Remotes.Rebirth:FireServer(unpack(args))

wait()
        end
    end)
end
